### ISSUE TITLE
Formatowanie kodu

### ISSUE THREAD

**Issue by wirtaw** [VValdemarJS/Algorytmy_i_struktury-danych#2]
https://github.com/VValdemarJS/Algorytmy_i_struktury-danych/blob/bb45c90d5e1819e9d762f13bca0d1dca16c26da4/Laboratorium/2022-10-11/Tablicy_Zadanie_2.c#L19

Zazwyczaj w redaktorach kodu jest opcja formatowania kodu.
W ReplIt.com tez taka jest. Proponja panu ja uzywac przed publikacja koda zrodlowego.

![Screenshot at 2022-10-12 23-42-57](https://user-images.githubusercontent.com/963873/195444540-008d7b1d-93a5-4ffe-8e1a-e12528770ec8.png)
![Screenshot at 2022-10-12 23-43-06](https://user-images.githubusercontent.com/963873/195444544-26be94f2-d18a-4954-ac5f-394a2efd2ead.png)

**Comment by VValdemarJS** [comment]
Dziekuje, zrozumialem.
