### ISSUE TITLE
wykonywać obliczenie w for pętli w której jest wprowadzane dane

### ISSUE THREAD

**Issue by wirtaw** [VValdemarJS/Algorytmy_i_struktury-danych#3]
https://github.com/VValdemarJS/Algorytmy_i_struktury-danych/blob/8e263c1f182ea2df61726bf94d6931956494ad81/Laboratorium/2022-10-11/Tablicy_Zadanie_3.c#L45

Jest jednakowe od i=0 do n i niema warunku żeby dwa razy byli zrealizowane.

**Comment by VValdemarJS** [comment]
Niebardzo rozumiem co ma pan na mysli, czy moglby pan inaczej wytlumaczyc?

**Comment by wirtaw** [comment]
U pana 26 i 48 linijka:
```c
  printf("\n");
  
  for(int i =0; i < n; i++){
    printf("wprowadz liczba X(%d) = ", i);
    scanf("%f", &x[i]);
  }

  printf("\n\n");

  printf("Wartość stałej a: %0.2f", a);
  
  printf("\n");

  for(int i = 0; i < n; i++){
    printf("Wartosc w tablicy X(%d): %0.2f\n", i, x[i]);
  }

  printf("\n");

  for(int i = 0; i < n; i++){
    y = a * x[i] * x[i];
    printf("y = %0.2f\n", y);
  }
```
czemu nie wykonac za jedna petla for

```c
  for(int i =0; i < n; i++){
    printf("wprowadz liczba X(%d) = ", i);
    scanf("%f", &x[i]); 
    printf("Wartosc w tablicy X(%d): %0.2f\n", i, x[i]);
    y = a * x[i] * x[i];
    printf("y = %0.2f\n", y);
  }

  printf("\n\n");

  printf("Wartość stałej a: %0.2f", a);
  
  printf("\n");
```
zamiast 3n iteracii tylko n

**Comment by VValdemarJS** [comment]
Teraz rozumiem, dziekuje.
Tak pisalem zeby w konsoli to wygladalo troszeczke "ladniej"

Wczesniej nigdy nad tym nie zastanawialem sie nawet
